version: "3.9"

x-common-variables: &common-variables
  DOCKER_USERNAME: test
  DOCKER_PASSWORD: test
  DOCKER_REGISTRY: registry:5000
  DOCKER_IMAGE: dump
  TZ: Europe/Paris
  MYSQL_HOST: db
  MYSQL_ROOT_PASSWORD: root

services:
  static:
    image: rtsp/lighttpd
    volumes:
      - ./test/static/:/var/www/html:ro
  registry:
    image: registry:2
  db:
    image: ghcr.io/linuxserver/mariadb:latest
    environment:
      <<: *common-variables
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MARIADB_AUTO_UPGRADE: "true"
      REMOTE_SQL: http://static/init.sql
    volumes:
      - database:/config
  backup:
    image: nouchka/dbdump
    build: .
    privileged: true
    environment:
      <<: *common-variables
      DATABASE_BACKUP: 1
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./test/docker/daemon.json:/etc/doc
      - /var/run/docker.sock:/var/run/docker.sock:ro
  init:
    image: nouchka/dbdump
    build: .
    privileged: true
    environment:
      <<: *common-variables
      DATABASE_INIT: 1
      MYSQL_DATABASE: restoredb
      MYSQL_USER: restore
      MYSQL_PASSWORD: restore
    volumes:
      - ./test/docker/daemon.json:/etc/doc
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  database:
