version: "3.9"

services:
  static:
    image: rtsp/lighttpd
    volumes:
      - ./test/static/:/var/www/html:ro
  registry:
    image: registry:2
  db:
    image: ghcr.io/linuxserver/mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MARIADB_AUTO_UPGRADE=true
      - TZ=Europe/Paris
      - REMOTE_SQL=http://static/init.sql
    volumes:
      - database:/config
  backup:
    image: nouchka/dbdump
    build: .
    privileged: true
    environment:
      - DATABASE_BACKUP=1
      - TZ=Europe/Paris
      - MYSQL_HOST=db
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - DOCKER_REGISTRY=registry:5000
      - DOCKER_IMAGE=dump
      - DOCKER_USERNAME=test
      - DOCKER_PASSWORD=test
  init:
    image: nouchka/dbdump
    build: .
    privileged: true
    environment:
      - DATABASE_INIT=1
      - TZ=Europe/Paris
      - MYSQL_HOST=db
      - MYSQL_DATABASE=restoredb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=restore
      - MYSQL_PASSWORD=restore
    volumes:
      - ./test/docker/daemon.json:/etc/docker/daemon.json:ro

volumes:
  database:
