version: "3.4"

services:
  static:
    image: rtsp/lighttpd
    volumes:
      - ./test/static/:/var/www/html:ro
  registry:
    image: registry:2
  db:
    image: ghcr.io/linuxserver/mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MARIADB_AUTO_UPGRADE=true
      - TZ=Europe/Paris
      - REMOTE_SQL=http://static/init.sql
    volumes:
      - database:/config
  backup:
    image: nouchka/dbdump
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ=Europe/Paris
      - DOCKER_REGISTRY=registry:5000
      - DOCKER_IMAGE=dump
##      - DOCKER_MODS=linuxserver/mods:universal-docker-in-docker
##      - DOCKER_USERNAME=
##      - DOCKER_PASSWORD=
    volumes:
      - ./test/docker/daemon.json:/etc/docker/daemon.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  database:
