version: "3.4"

services:
  static:
    image: rtsp/lighttpd
    volumes:
      - ./test/static/:/var/www/html:ro
  registry:
    image: registry:2
  db:
    image: ghcr.io/linuxserver/mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MARIADB_AUTO_UPGRADE=true
      - TZ=Europe/Paris
      - REMOTE_SQL=http://static/init.sql
    volumes:
      - database:/config
  backup:
    build: .
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ=Europe/Paris
      - DOCKER_MODS=linuxserver/mods:universal-docker-in-docker
      - DOCKER_USERNAME=
      - DOCKER_PASSWORD=
      - DOCKER_REGISTRY=registry.gitlab.com
      - DOCKER_IMAGE=registry:5000/dump
    volumes:
      - ./test/docker/daemon.json:/etc/docker/daemon.json:ro

volumes:
  database:
