#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ "$DATABASE_INIT" == "1" && -f "/data/dump.sql.gz" ]] ; then
	echo "Mysql lock"
	mysql -uroot -p$MYSQL_ROOT_PASSWORD -h $MYSQL_HOST -e "ALTER USER $MYSQL_USER@'%' ACCOUNT LOCK;" || true

	echo "Mysql import"
	zcat /data/dump.sql.gz |mysql -uroot -p$MYSQL_ROOT_PASSWORD -h $MYSQL_HOST $MYSQL_DATABASE

	echo "Mysql unlock"
	mysql -uroot -p$MYSQL_ROOT_PASSWORD -h $MYSQL_HOST -e "ALTER USER $MYSQL_USER@'%' ACCOUNT UNLOCK;" || true
elif [[ ! -z $DOCKER_REGISTRY && ! -z $DOCKER_IMAGE ]] ; then
	echo "Mysql dump"
	mysqldump -uroot -p$MYSQL_ROOT_PASSWORD -h $MYSQL_HOST $MYSQL_DATABASE| gzip > /root/build/data/dump.sql.gz

	echo "Docker build"
	cd /root/build && docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE .

	echo "Docker login"
	echo $DOCKER_PASSWORD| /usr/local/bin/docker login $DOCKER_REGISTRY --username $DOCKER_USERNAME --password-stdin || true

	echo "Docker push: $DOCKER_REGISTRY/$DOCKER_IMAGE"
	docker push $DOCKER_REGISTRY/$DOCKER_IMAGE

	echo "Docker clean"
	docker rmi $DOCKER_REGISTRY/$DOCKER_IMAGE
fi

echo "Halting"
/run/s6/basedir/bin/halt
